import '../styles/globals.css'
import App, { AppProps } from 'next/app'
import Head from 'next/head'
import { Layout, LayoutProps } from 'src/components'
import { API_ENDPOINTS } from 'shared'
import { GetServerSideProps } from 'next'

const { GENRES: GENRES_END_POINT } = API_ENDPOINTS

interface Props extends Omit<LayoutProps, 'children'> {}

export declare type AppInitialProps<T = unknown> = {
  pageProps: T;
};

function MyApp({ Component, pageProps }: AppProps<Props>) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout allGenres={pageProps?.allGenres}>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

MyApp.getInitialProps = async (): Promise<AppInitialProps<Props>> => {
  const res = await fetch(GENRES_END_POINT)
  const { genres: allGenres } = (await res.json())

  return {
    pageProps: { allGenres }
  }
}

export default MyApp
